### ISSUE TITLE
SMX and ModManager not working with patch.

### ISSUE THREAD

**Issue by HeavyDeception** [FilUnderscore/ModManager#1]
Ok was wondering if I could have a hand with the Modmanager mod when using it with SMX when I install it and the Support pack for it all the menu buttons will stack on top of one another and the menu will not load correctly.

[This is just the ui mods I use and the mod manager and it does the same thing.](https://puu.sh/JjHK8/f51e0d7c14.png)

**Comment by FilUnderscore** [comment]
Hi, is there a screenshot of the menu that you could provide showing the issue? Additionally, is there any error that pops up in the console?

**Comment by HeavyDeception** [comment]
There are no error popping up I have alt F4 to close the game will send you a screen shot in a bit.

**Comment by HeavyDeception** [comment]
[These are the mods I'm running.](https://puu.sh/JjRMI/9990af8661.png)

[This is what it looks like now I don't know why it's working but 2 of the SMX mods are no longer running (SMXmenu & SMXui but I do have them installed.](https://puu.sh/JjROM/5eb2a5cc0e.jpg)

If I remove ModManager and ModManager SMX Support they work. 
[Game Menu](https://puu.sh/JjRQz/1d5534f0a6.jpg)
[Folder With Mods Removed](https://puu.sh/JjRRd/6bd2b57efc.png)

**Comment by FilUnderscore** [comment]
> [This is what it looks like now I don't know why it's working but 2 of the SMX mods are no longer running (SMXmenu & SMXui but I do have them installed.](https://puu.sh/JjROM/5eb2a5cc0e.jpg)

Seems like they are still running, but SMX reports them as not running as they load after SMXcore (this is just a visual bug). This may be related to a similar issue to do with load order not following the alphanumerical name of folders, which is being fixed in the next update 1.0.3. However, I'm unsure of

> menu buttons will stack on top of one another and the menu will not load correctly.

as I have not been able to recreate the issue and there seems to be no screenshot of it/error in the logs that indicate the problem. I will continue to look deeper into it, however see if it still happens when the next release comes out.

There is a temporary fix to the load order through the following:

> In the meantime, you could add mods as dependencies inside their own Manifest.xml in each mod folder that isn't loading in the correct order, to "parent" them to a certain mod. Here's some info from the wiki on how to go about it: https://github.com/FilUnderscore/ModManager/wiki/Mod-Integration#dependency-management
>
> This is just a temporary fix though, and it will be fixed in the next update. 

Not sure if this will fix the UI buttons stacking on top of each other however.

**Comment by HeavyDeception** [comment]
I will look into it if I see them stacked again I will get a screen shot and try to get you the logs.

**Comment by FilUnderscore** [comment]
Please re-open this issue if it is still happening in the latest update 1.0.3. Thanks.
